### ISSUE TITLE
no such file or directory index.html

### ISSUE THREAD

**Issue by Mtea994** [proofofexistence/proofofexistence#66]
why am i getting this error with nodejs local deployment any idea ???

 Proof of Existence listening at http://:::3004
[1] (node:8380) UnhandledPromiseRejectionWarning: OpenError: IO error: LockFile /tmp/poex-database-test/LOCK: The system cannot find the path specified.
[1]
[1]     at C:\Users\Mtea994\Downloads\Compressed\proofofexistence-master\proofofexistence-master\node_modules\levelup\lib\levelup.js:91:23
[1]     at C:\Users\Mtea994\Downloads\Compressed\proofofexistence-master\proofofexistence-master\node_modules\abstract-leveldown\abstract-leveldown.js:41:14
[1]     at C:\Users\Mtea994\Downloads\Compressed\proofofexistence-master\proofofexistence-master\node_modules\deferred-leveldown\deferred-leveldown.js:20:21
[1]     at C:\Users\Mtea994\Downloads\Compressed\proofofexistence-master\proofofexistence-master\node_modules\abstract-leveldown\abstract-leveldown.js:41:14
[1]     at C:\Users\Mtea994\Downloads\Compressed\proofofexistence-master\proofofexistence-master\node_modules\leveldown\node_modules\abstract-leveldown\abstract-leveldown.js:39:16
[1] (node:8380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[1] (node:8380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1] GET / 404 14.029 ms - 290
[1] Error: ENOENT: no such file or directory, stat 'C:\Users\Mtea994\Downloads\Compressed\proofofexistence-master\proofofexistence-master\ui\public\index.html'

**Comment by qinfengling** [comment]
@Mtea994 index.html was build through `npm run build`.
if you still have problems, you can follow the [install guide](https://docs.proofofexistence.com/#/get-started?id=get-started)

**Comment by Mtea994** [comment]
![image](https://user-images.githubusercontent.com/20420633/52390731-df975a80-2abb-11e9-93f7-7f42d673a42f.png)
![image](https://user-images.githubusercontent.com/20420633/52390769-11102600-2abc-11e9-8787-511ddcb88981.png)
i think there is some kind of error in abstract level down js library type of process is not defined i have windows 10 operating system do you think it might be causing this issue

**Comment by Mtea994** [comment]
> ![image](https://user-images.githubusercontent.com/20420633/52390731-df975a80-2abb-11e9-93f7-7f42d673a42f.png)
> ![image](https://user-images.githubusercontent.com/20420633/52390769-11102600-2abc-11e9-8787-511ddcb88981.png)
> i think there is some kind of error in abstract level down js library type of process is not defined i have windows 10 operating system do you think it might be causing this issue

@qinfengling

**Comment by qinfengling** [comment]
@Mtea994 Sorry, I am not sure about the development tools in windows.
Do you have Linux or macOS ? 
if not, you can also run it under MSYS2 (UNIX like shell)

**Comment by qinfengling** [comment]
@Mtea994 It is not an easy way to support it in Windows.

We'v test it in MYSYS2 without success.

```bash
pacman -S git mingw-w64-x86_64-nodejs python2

npm install --global --production windows-build-tools
npm config set python "C:\Users\USERNAME\.windows-build-tools\python27\python.exe"
npm install --global node-gyp
npm install
```

Thanks for your new issue.

We have update the known issues to README
https://github.com/proofofexistence/proofofexistence/blob/master/README.md#known-issues
